# Generated by Django 4.0.3 on 2022-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
