# Generated by Django 4.0.3 on 2022-04-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.IntegerField(choices=[(0, 'Mamiferos'), (1, 'Aves'), (2, 'Reptiles'), (3, 'Ranas y sapos')], default=0),
        ),
    ]
