# Generated by Django 4.0.3 on 2022-04-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_animal_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.CharField(default='Perro', max_length=50),
            preserve_default=False,
        ),
    ]
