# Generated by Django 4.0.3 on 2022-05-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_animal_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
