# Generated by Django 4.0.3 on 2022-05-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cliente_options_alter_cliente_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
