# Generated by Django 4.0.3 on 2022-05-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='duenio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapp.cliente'),
            preserve_default=False,
        ),
    ]
