# Generated by Django 4.0.3 on 2022-05-10 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_animal_created_at_animal_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_consulta', models.DateTimeField()),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.animal')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.enfermedad')),
            ],
        ),
    ]
