# Generated by Django 4.0.3 on 2022-05-10 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_enfermedad_alter_animal_options_consulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-fecha_de_consulta']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_de_consulta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
